### PR TITLE
Change depletion time step sizes

### PR DESCRIPTION
**Pull request by abachma2**
This PR changes the depletion time step size for OpenMC from assuming each time step is 30 days to using the `dt` parameter in Cyclus to define the time step size.

### CODE REVIEW

**Review by nsryan2 — APPROVED** [review]
LGTM!

**Comment by abachma2** [comment]
Not at the moment. That would fall under the integration tests, which aren't working because of the seg fault (see #12).

**Comment by nsryan2** [comment]
Gottcha, I'm happy to merge. I'll make a note in that issue so it doesn't get lost.

**Comment by nsryan2** [comment]
Would you want this part of the unit test to be updated? https://github.com/arfc/openmcyclus/blob/3723a289f14f1061e38752ee6ba3d6b8205bf316/tests/unit_tests/test_depletion.py#L48C13-L51C32

**Comment by abachma2** [comment]
No. That function is to run the depletion solver just for the unit tests. It's not connected to the method in Cyclus to call the depletion solver. I can't update the test function to match with the Cyclus method because the `dt` parameter is only available in-situ of a Cyclus run.

**Comment by nsryan2** [comment]
Ok, merging!

**Pull request merged**
